Pipeline processor
henryzhx8/ilogtail pull request #2
Opened 2023-11-17 05:44 UTC by quzard

2023-11-18 09:45 UTC, henryzhx8 requested changes
几点共性的：
1. cpp文件都么都用using namespace std要么都不用；
2. 重构不是简单的代码搬家，是了解原有代码逻辑之后进行重新整理，改调用点是让你直接用新参数，不是把新参数转成老参数，如果每一次修改都加这么一层转换逻辑，屎山很快就堆出来了

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.h
>      bool mEnableLogPositionMeta = false;
```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    }
```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    mSplitKey = DEFAULT_CONTENT_KEY;
默认值移到类定义那，这边也要从config来解析这个参数

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    }
```suggestion
    int32_t splitter;
    if (!GetOptionalIntParam(config, "SplitChar", splitter, errorMsg)) {
        PARAM_WARNING_DEFAULT(mContext->GetLogger(), errorMsg, "\\n", sName, mContext->GetConfigName());
    } else {
        mSplitChar = static_cast<char>(splitter);
    }
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/common/ParamExtractor.h
> +bool IsExist(const Json::Value& config, const std::string& key);
这个我觉得没有必要
```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/common/ParamExtractor.cpp
> +}
```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    bool mIsMultline;
这些参数连带下面的ptr直接用Multiline类替换吧，不要重复逻辑了

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +    mIsMultline = IsMultiline();
Multiline.Init()

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +    std::string mRenamedSourceKey = "";
```suggestion
    std::string mRenamedSourceKey;
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +    bool mCopingRawLog = false;
这四个单独放一个struct体，叫CommonParserOptions，各个地方引用，避免重复代码

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +    static const std::string UNMATCH_LOG_KEY;
包括这个常量也放到CommonParserOptions里

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    }
漏了正则合法性校验，原来configmanagerbase里面校验的逻辑必须全部搬过来，不要漏

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    }
看一下regex的括号数量和keys的数量不匹配能不能快速的发现

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +        mRenamedSourceKey = mSourceKey;
这一行放构造函数里

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +};
这个结构明显是多余的，以前设计余量是允许多套正则匹配的，现在插件化了只需要一个了，把相关代码都删了或重构下

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +};
这个还有地方用？

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
>      bool mRawLogTagOverwritten = false;
我理解没用，所有插件都删了

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseJsonNative.cpp
>          return true;
太绕了，简单点
```suggestion
    if ((parseSuccess && mKeepingSourceWhenParseSucceed || !parseSuccess && mKeepingSourceWhenParseFail) && mSourceKey != mRenamedSourceKey) {
        if (!mSourceKeyOverwritten) {
            sourceEvent.DelContent(mSourceKey);
        }
        AddLog(mRenamedSourceKey, rawContent, sourceEvent, false);
    }
    // legacy behavior
    if (!parseSuccess && mKeepingSourceWhenParseFail && mCopingRawLog) {
        AddLog(UNMATCH_LOG_KEY, rawContent, sourceEvent, false);
        return true;
```
另外，这段逻辑也应该整体打包函数放到CommonParserOptions里，各个地方复用

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.h
> +    enum class Method { extend, keep, discard };
枚举值统一用大写，类名直接改成OverflowedFieldsTreatment

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.h
> +    std::string mOverflowedFieldsTreatment = "extend";
用枚举类

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.h
>      bool mRawLogTagOverwritten = false;
这些还保留？

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    }
仿照flushersls里面关于枚举值的初始化写法

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        mSeparator = '\t';
标注一下向前兼容的原因

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    }
这个没必要，getmandatorystring会检查是否为空

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    if (mSeparator.size() == 1) {
separator大于1，且配了quote的情况，要报warning

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +            mQuote = quoteStr[0];
多余的

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        std::string quoteStr = "\"";
```suggestion
        std::string quoteStr;
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +            errorMsg = "quote for Delimiter Log only support single char(like \")";
```suggestion
            errorMsg = "param Quote is not a single char";
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    }
都没必要

```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.h
> +    bool mAdjustingMicroTimezone = false;
这个参数废弃了，统一为true

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.cpp
> +                         "module", sName)("config", mContext->GetConfigName())("offset seconds", logTZSecond));
```suggestion
```

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.cpp
> +            mLogTimeZoneOffsetSecond = logTZSecond;
挪到timezone那个分支那边

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.cpp
> +        if (!ProcessorParseTimestampNative::ParseTimeZoneOffsetSecond(mTimezone, logTZSecond)) {
这个函数挪到TimeUtil里面，尽量不要出现插件之间相互用函数的情况

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseTimestampNative.h
> +    int mSourceYear = -1;
int32_t

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorParseTimestampNative.h
>      PreciseTimestampConfig mLegacyPreciseTimestampConfig;
这个也废弃掉了，不要了

2023-11-18 09:45 UTC, henryzhx8 commented on core/processor/ProcessorTagNative.h
>      bool mPluginProcessFlag = false;
```suggestion
```

2023-11-18 09:47 UTC, henryzhx8 reviewed
几点共性的：
1. cpp文件都么都用using namespace std要么都不用；
2. 重构不是简单的代码搬家，是了解原有代码逻辑之后进行重新整理，改调用点是让你直接用新参数，不是把新参数转成老参数，如果每一次修改都加这么一层转换逻辑，屎山很快就堆出来了

2023-11-19 09:53 UTC, quzard commented on core/processor/ProcessorSplitRegexNative.cpp
> +    mIsMultline = IsMultiline();
用不了

2023-11-21 08:02 UTC, henryzhx8 requested changes

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.cpp
> +    int32_t splitter = '\n';
加一行注释 // SplitChar

2023-11-21 08:02 UTC, henryzhx8 commented on core/file_server/MultilineOptions.h
> +    std::shared_ptr<boost::regex> mContinuePatternRegPtr;
移到public的原因？不是有函数给你拿私有成员了吗？

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +                    } else if (mMultiline.mStartPatternRegPtr != nullptr) {
都用函数拿，别直接用私有成员

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.h
> +    std::string mRenamedSourceKey = "__raw__";
这是什么情况？默认值是mSourceKey啊，和__raw__有啥关系

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    } else if (!CheckRegFormat(mRegex)) {
paramExtractor里有IsRegexValid函数可以用

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +        PARAM_ERROR_RETURN(mContext->GetLogger(), errorMsg, sName, mContext->GetConfigName());
```suggestion
        PARAM_ERROR_RETURN(mContext->GetLogger(), "param Regex is not valid regex", sName, mContext->GetConfigName());
```

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseJsonNative.h
> +    std::string mRenamedSourceKey = "__raw__";
一样

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseJsonNative.h
> +#include "rapidjson/document.h"
这是第三方库

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.h
> +    char mQuote = '\"';
这个必须要加\吗？

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.h
> +    std::string mRenamedSourceKey = "__raw__";
一样

2023-11-21 08:02 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.cpp
> +    mMultiline.Init(config, *mContext, sName);
这边可以优化一下，不用再反复解析同一个东西了，直接新增一个Init函数，入参就是const Multiline&

2023-11-22 02:08 UTC, henryzhx8 requested changes

2023-11-22 02:08 UTC, henryzhx8 commented on core/file_server/MultilineOptions.h
> +#include "json/json.h"
json是第三方库，空行

2023-11-22 02:08 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +#include "processor/daemon/LogProcess.h"
这个应该还在原位置吧？

2023-11-22 02:08 UTC, henryzhx8 commented on core/pipeline/Pipeline.cpp
> +            detail["Multiline.EndPattern"] = Json::Value(inputFile->mMultiline.mEndPattern);
这边直接把multiline传给插件吧

2023-11-22 02:08 UTC, henryzhx8 commented on core/common/TimeUtil.h
> +                                  bool isAdjustmentNeeded);
这种工具函数，不要把ctx和pluginName传进来，打日志由插件完成，不要在这里打，可以将返回值改成bool

2023-11-22 02:08 UTC, henryzhx8 commented on core/common/CommonParserOptions.h
> +    bool ShouldAddUnmatchLog(const bool& parseSuccess) {
bool 不需要const &

2023-11-22 02:08 UTC, henryzhx8 commented on core/common/CommonParserOptions.h
> +    bool Init(const Json::Value& config, const PipelineContext& ctx, const std::string& pluginName);
函数放一块

2023-11-22 02:08 UTC, henryzhx8 commented on core/common/CommonParserOptions.h
> +class CommonParserOptions {
都是public的话，直接struct吧

2023-11-22 02:08 UTC, henryzhx8 commented on core/common/CommonParserOptions.h
> +    }
这三个。。。

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorSplitLogStringNative.h
> +} // namespace logtail
文件尾巴空行都需要的

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    bool IsMultiline() const;
有用到？

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    bool ParseRegex(const std::string& pattern, std::shared_ptr<boost::regex>& reg);
这个呢？

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    // const UserDefinedFormat& format = mUserDefinedFormat[i];
不要的就删了

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
>      const StringView& logPath = logGroup.GetMetadata(EventGroupMetaKey::LOG_FILE_PATH_RESOLVED);
75行那个类前缀不用，删了吧

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
>      mProcDiscardRecordsTotal->Add(1);
这个移到外层函数

2023-11-22 02:08 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    if (parseSuccess || mCommonParserOptions.mKeepingSourceWhenParseFail) {
这边改一下逻辑

2023-11-24 08:45 UTC, henryzhx8 requested changes

2023-11-24 08:45 UTC, henryzhx8 commented on core/common/ParamExtractor.cpp
> +
这个是不是没用到？

2023-11-24 08:45 UTC, henryzhx8 commented on core/processor/CommonParserOptions.h
> +    }
```suggestion
    bool ShouldAddSourceContent(bool parseSuccess) {
        return (parseSuccess && mKeepingSourceWhenParseSucceed) || (!parseSuccess && mKeepingSourceWhenParseFail);
    }
```

2023-11-24 08:45 UTC, henryzhx8 commented on core/processor/ProcessorParseRegexNative.cpp
> +    if (mCommonParserOptions.ShouldAddRenamedSourceLog(parseSuccess, mSourceKey)) {
```suggestion
    if (!parseSucess || !mSourceKeyOverwritten) {
        sourceEvent.DelContent(mSourceKey);
    }
    if (mCommonParserOptions.ShouldAddRenamedSourceLog(parseSuccess)) {
        AddLog(mCommonParserOptions.mRenamedSourceKey, rawContent, sourceEvent, false);
   }
```

2023-11-27 04:07 UTC, henryzhx8 requested changes

2023-11-27 04:07 UTC, henryzhx8 commented on core/models/PipelineEventGroup.h
> +#endif
挪回去

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/CommonParserOptions.h
> +    bool ShouldEraseEvent(bool parseSuccess, const LogEvent& sourceEvent);
struct的话，先放成员变量，再放函数，所以把Init挪下来

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/CommonParserOptions.h
> +#endif
这个也可以删了
```suggestion
```

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorSplitRegexNative.h
> +    CommonParserOptions mCommonParserOptions;
这个别复用这个参数了

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        errorMsg = "param Quote is not allowed when Separator length is more than 1";
这里是不是有问题？没有Quote字段的话，res也是true吧

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    }
挪到上边separator那边吧，逻辑紧凑些

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        mSeparatorChar = '\t';
这种绝对不会happen的，删了吧

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        if (key.compare(mSourceKey) == 0) {
这里为啥和正则那边的写法不一样？

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    mAutoExtend = mOverflowedFieldsTreatment == OverflowedFieldsTreatment::EXTEND;
这个参数为什么还要保留？

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +    mExtractPartialFields = mOverflowedFieldsTreatment == OverflowedFieldsTreatment::DISCARD;
这个参数是要保留的，因为有点兼容性的原因

2023-11-27 04:07 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.h
> +    static const int32_t MAX_BASE_FIELD_NUM;
这个是不是可以放cpp里？

2023-11-27 05:36 UTC, henryzhx8 requested changes

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseDelimiterNative.cpp
> +        } else {
没配Quote呢？

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.h
> +    bool mAdjustingMicroTimezone = true;
这个一样也废弃掉了

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.cpp
> +    mSourceKeyOverwritten = false;
这个有用到吗？

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseTimestampNative.h
> +    static const std::string PRECISE_TIMESTAMP_DEFAULT_KEY;
这个也没用了

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseTimestampNative.cpp
> +                mContext->GetLogger(), errorMsg, mLogTimeZoneOffsetSecond, sName, mContext->GetConfigName());
同前

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorParseTimestampNative.cpp
> +} // namespace logtail
换行符

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorFilterNative.h
这个里面长的函数放到cpp里面吧

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorFilterNative.cpp
> +    if (GetOptionalMapParam(config, "Include", mInclude, errorMsg) && !mInclude.empty()) {
漏了Include非法的情况

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorFilterNative.h
> +    enum class Mode { BYPASS_MODE, EXPRESSION_MODE, RULE_MODE };
BYPASS是干啥用的？

2023-11-27 05:36 UTC, henryzhx8 commented on core/processor/ProcessorDesensitizeNative.cpp
> +        mContext->GetAlarm().SendAlarm(CATEGORY_CONFIG_ALARM,
alarm不需要，后边统一加

2023-11-27 14:11 UTC, quzard commented on core/processor/ProcessorParseApsaraNative.h
> +    bool mAdjustingMicroTimezone = true;
跟mAdjustingMicroTimezone有关的代码呢
if (mAdjustingMicroTimezone) {
        logTime_in_micro = (int64_t)logTime_in_micro - (int64_t)mLogTimeZoneOffsetSecond * (int64_t)1000000;
    }

2023-11-27 14:11 UTC, quzard commented on core/processor/ProcessorParseApsaraNative.cpp
> +    mSourceKeyOverwritten = false;
有用到，这里是设置初始值为false

2023-11-27 14:30 UTC, quzard commented on core/processor/ProcessorFilterNative.h
> +    enum class Mode { BYPASS_MODE, EXPRESSION_MODE, RULE_MODE };
用来判断是否配置了过滤

2023-11-28 06:57 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.h
> +    bool mAdjustingMicroTimezone = true;
默认为true

2023-11-28 09:41 UTC, henryzhx8 approved these changes

2023-11-28 09:41 UTC, henryzhx8 commented on core/processor/ProcessorParseApsaraNative.cpp
> +    //     logTime_in_micro = (int64_t)logTime_in_micro - (int64_t)mLogTimeZoneOffsetSecond * (int64_t)1000000;
这个默认为true

2023-11-30 08:43 UTC, merged